### ISSUE TITLE
missende afbeeldingen in de photohub

### ISSUE THREAD

**Issue by Pietto** [davinci-ao/mbw-almanac#23]
images die geupload worden door de gebruiker worden niet weergegeven in de photohub 
dit probleem doet zich alleen voor op de azure omgeving
gevonden tijdens het programmeren
gevonden door: Pieterjan van Dijk

Stappen naar reproduceren:
-navigeer naar https://mbw-almanac.azurewebsites.net/
-login of registreer een account
-klik op de tab 'photohub' bovenin de header.
-klik op de 'image icon' rechtsbovenin de header
-upload een foto en kies evt. een titel
-u word terug genavigeerd naar de photohub, waar alle geuploade images staan, zonder image om weer te geven

verwacht: Geen technische foutmeldingen zichtbaar voor de gebruiker, wel groot ongemak omdat een fundamentele eis van de photohub niet werkt.

images worden nog geladen vanuit de directory
mogelijke oplossing: blob storage
^needs more research

issue nog niet opgelost

**Comment by AyaMohammad** [comment]
als je kijkt bij de favorite images model, dan kan je daar zien dat er een veld in de database staat van image die het type text heeft, en in de controller word dat opgeslagen en als base64 string. als je dan in de blade file van favorite-images/index.blade.php kijkt kan je zien hoe die base64 word uitgelezen, is wat makkelijker bruikbaar ipv blob, blob is vaak alleen voor echt groote files.

**Comment by Pietto** [comment]
issue opgelost, images worden lokaal in de directory opgeslagen, en een row in de DB word aangemaakt. de directory waar de images werden opgeslagen was buiten de public, vanwege security reasons weigert azure toegang buiten de public folder. het pad waar de images nu in de directory worden opgeslagen is aangepast naar 'public/uploads/image'
