### ISSUE TITLE
#2 (Azure) bij het openen van de homepage vanuit de profiel pagina komt er een wit scherm

### ISSUE THREAD

**Issue by Pietto** [davinci-ao/mbw-almanac#40]
bij het openen van de homepage vanuit de profiel pagina komt er een wit scherm. dit probleem doet zich alleen voor op de azure omgeving.
gevonden tijdens het testen op Azure
gevonden door Pieterjan

stappen tot reproductie:
- registreer of login met je account
- open je account pagina door op je naam te klikken
- navigeer terug door op Home te klikken in je linker navbar
- een verschijnt geen error scherm, alleen een wit scherm

verwachting: geen foutmelding voor de gebruiker, wel kan de gebruiker niet door navigeren over de site.

**Comment by Pietto** [comment]
update: issue doet zich voor op alle pagina's, niet alleen op de profiel pagina

**Comment by Pietto** [comment]
![Capture](https://user-images.githubusercontent.com/42929234/143032167-cdbfee21-a463-45ae-96c9-15fb35272e60.PNG)

**Comment by KantSjaak** [comment]
Bedankt voor de url! 😄 ❤️
